// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './basscatelogcard.css';


export default class Basscatelogcard extends React.Component {
  render() {
    return (
      <div className="basscatelogcard-basscatelogcard-0">
          <div className="basscatelogcard-0">
              <div className="basscatelogcard-basscontent_maincontent_catelog_item4">
                  <div className="basscatelogcard-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/29d5/1ea3/29e51a73b063b42b1a47e84ab64a2922" className="basscatelogcard-image-1" /> 
                  </div>
                  <div className="basscatelogcard-0-0-1">
                      <div className="basscatelogcard-fender_limited_edition_american_elite_jazz_bass_v_matching_headcap_maple_fingerboard_surf_pearl-0">
                          Fender Limited Edition American Elite Jazz Bass V Matching Headcap Maple Fingerboard Surf Pearl
                      </div>
                  </div>
                  <div className="basscatelogcard-0-0-2">
                      <div className="basscatelogcard-guitarcontent_maincontainer_catelog_stars-0">
                          <div className="basscatelogcard-0-0-2-0-0">
                              <div className="basscatelogcard-rectangle_2">
                                  <div className="basscatelogcard-0-0-2-0-0-0-0">
                                      <div className="basscatelogcard-2">22 Reviews</div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="basscatelogcard-0-0-3">
                      <div className="basscatelogcard-_2">$2099.99</div>
                  </div>
                  <div className="basscatelogcard-0-0-4">
                      <div className="basscatelogcard-guitarciontent_maincontainer_catelog_compare-0">
                          <div className="basscatelogcard-0-0-4-0-0">
                              <div className="basscatelogcard-0-0-4-0-0-0">
                                  <div className="basscatelogcard-0-0-4-0-0-0-0">
                                      <div className="basscatelogcard-rectangle_2-0" /> 
                                  </div>
                              </div>
                              <div className="basscatelogcard-compare-0">Compare</div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
