// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './basscontent_maincontent_catelog_item2.css';


export default class Basscontent_maincontent_catelog_item2 extends React.Component {
  render() {
    return (
      <div className="basscontent_maincontent_catelog_item2-basscontent_maincontent_catelog_item2">
          <div className="basscontent_maincontent_catelog_item2-0">
              <div className="basscontent_maincontent_catelog_item2-rectangle-0">
                  <div className="basscontent_maincontent_catelog_item2-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/ab20/35af/8d6b496cc35133bccb4bd5d5de027a48" className="basscontent_maincontent_catelog_item2-image-0" /> 
                  </div>
                  <div className="basscontent_maincontent_catelog_item2-0-0-1">
                      <div className="basscontent_maincontent_catelog_item2-ibanez_gsrm2">
                          Ibanez GSRM20 Mikro Short-Scale Bass Guitar
                      </div>
                  </div>
                  <div className="basscontent_maincontent_catelog_item2-0-0-2">
                      <div className="basscontent_maincontent_catelog_item2-rectangle_2">
                          <div className="basscontent_maincontent_catelog_item2-0-0-2-0-0">
                              <div className="basscontent_maincontent_catelog_item2-guitarcontent_maincontainer_catelog_stars-0">
                                  <div className="basscontent_maincontent_catelog_item2-0-0-2-0-0-0-0">
                                      <div className="basscontent_maincontent_catelog_item2-2">
                                          22 Reviews
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="basscontent_maincontent_catelog_item2-0-0-3">
                      <div className="basscontent_maincontent_catelog_item2-starting_at_1">
                          Starting at $159.99
                      </div>
                  </div>
                  <div className="basscontent_maincontent_catelog_item2-0-0-4">
                      <div className="basscontent_maincontent_catelog_item2-guitarciontent_maincontainer_catelog_compare-0">
                          <div className="basscontent_maincontent_catelog_item2-0-0-4-0-0">
                              <div className="basscontent_maincontent_catelog_item2-0-0-4-0-0-0">
                                  <div className="basscontent_maincontent_catelog_item2-0-0-4-0-0-0-0">
                                      <div className="basscontent_maincontent_catelog_item2-rectangle_2-0" /> 
                                  </div>
                              </div>
                              <div className="basscontent_maincontent_catelog_item2-compare-0">
                                  Compare
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
