// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './basscatelogcard1.css';


export default class Basscatelogcard1 extends React.Component {
  render() {
    return (
      <div className="basscatelogcard1-basscatelogcard1">
          <div className="basscatelogcard1-0">
              <div className="basscatelogcard1-basscontent_maincontent_catelog_item1">
                  <div className="basscatelogcard1-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/a0be/951c/1f76807b8449e81a7318a07ee2a1027d" className="basscatelogcard1-image-7" /> 
                  </div>
                  <div className="basscatelogcard1-0-0-1">
                      <div className="basscatelogcard1-fender_special_edition_deluxe_pj_bass-0">
                          Fender Special Edition Deluxe PJ Bass
                      </div>
                  </div>
                  <div className="basscatelogcard1-0-0-2">
                      <div className="basscatelogcard1-guitarcontent_maincontainer_catelog_stars-0">
                          <div className="basscatelogcard1-0-0-2-0-0">
                              <div className="basscatelogcard1-rectangle_2">
                                  <div className="basscatelogcard1-0-0-2-0-0-0-0">
                                      <div className="basscatelogcard1-2">22 Reviews</div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="basscatelogcard1-0-0-3">
                      <div className="basscatelogcard1-_7">$799.99</div>
                  </div>
                  <div className="basscatelogcard1-0-0-4">
                      <div className="basscatelogcard1-guitarciontent_maincontainer_catelog_compare-0">
                          <div className="basscatelogcard1-0-0-4-0-0">
                              <div className="basscatelogcard1-0-0-4-0-0-0">
                                  <div className="basscatelogcard1-0-0-4-0-0-0-0">
                                      <div className="basscatelogcard1-rectangle_2-0" /> 
                                  </div>
                              </div>
                              <div className="basscatelogcard1-compare-0">Compare</div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
