// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './basscatelogcard3.css';


export default class Basscatelogcard3 extends React.Component {
  render() {
    return (
      <div className="basscatelogcard3-basscatelogcard3">
          <div className="basscatelogcard3-0">
              <div className="basscatelogcard3-basscontent_maincontent_catelog_item3">
                  <div className="basscatelogcard3-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/f3af/cf26/45c87662d1e4ff39ae29f9d60969d7e7" className="basscatelogcard3-image-5" /> 
                  </div>
                  <div className="basscatelogcard3-0-0-1">
                      <div className="basscatelogcard3-fender_usa_geddy_lee_signature_jazz_bass-0">
                          Fender USA Geddy Lee Signature Jazz Bass
                      </div>
                  </div>
                  <div className="basscatelogcard3-0-0-2">
                      <div className="basscatelogcard3-guitarcontent_maincontainer_catelog_stars-0">
                          <div className="basscatelogcard3-0-0-2-0-0">
                              <div className="basscatelogcard3-rectangle_2">
                                  <div className="basscatelogcard3-0-0-2-0-0-0-0">
                                      <div className="basscatelogcard3-2">22 Reviews</div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="basscatelogcard3-0-0-3">
                      <div className="basscatelogcard3-_1">$1599.99</div>
                  </div>
                  <div className="basscatelogcard3-0-0-4">
                      <div className="basscatelogcard3-guitarciontent_maincontainer_catelog_compare-0">
                          <div className="basscatelogcard3-0-0-4-0-0">
                              <div className="basscatelogcard3-0-0-4-0-0-0">
                                  <div className="basscatelogcard3-0-0-4-0-0-0-0">
                                      <div className="basscatelogcard3-rectangle_2-0" /> 
                                  </div>
                              </div>
                              <div className="basscatelogcard3-compare-0">Compare</div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
