// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './basscatelogcard2.css';


export default class Basscatelogcard2 extends React.Component {
  render() {
    return (
      <div className="basscatelogcard2-basscatelogcard2">
          <div className="basscatelogcard2-0">
              <div className="basscatelogcard2-basscontent_maincontent_catelog_item2">
                  <div className="basscatelogcard2-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/ab20/35af/8d6b496cc35133bccb4bd5d5de027a48" className="basscatelogcard2-image-2" /> 
                  </div>
                  <div className="basscatelogcard2-0-0-1">
                      <div className="basscatelogcard2-ibanez_gsrm2">
                          Ibanez GSRM20 Mikro Short-Scale Bass Guitar
                      </div>
                  </div>
                  <div className="basscatelogcard2-0-0-2">
                      <div className="basscatelogcard2-guitarcontent_maincontainer_catelog_stars-0">
                          <div className="basscatelogcard2-0-0-2-0-0">
                              <div className="basscatelogcard2-rectangle_2">
                                  <div className="basscatelogcard2-0-0-2-0-0-0-0">
                                      <div className="basscatelogcard2-2">22 Reviews</div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="basscatelogcard2-0-0-3">
                      <div className="basscatelogcard2-starting_at_1">
                          Starting at $159.99
                      </div>
                  </div>
                  <div className="basscatelogcard2-0-0-4">
                      <div className="basscatelogcard2-guitarciontent_maincontainer_catelog_compare-0">
                          <div className="basscatelogcard2-0-0-4-0-0">
                              <div className="basscatelogcard2-0-0-4-0-0-0">
                                  <div className="basscatelogcard2-0-0-4-0-0-0-0">
                                      <div className="basscatelogcard2-rectangle_2-0" /> 
                                  </div>
                              </div>
                              <div className="basscatelogcard2-compare-0">Compare</div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
