// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './basscontent_maincontent_catelog_item4.css';


export default class Basscontent_maincontent_catelog_item4 extends React.Component {
  render() {
    return (
      <div className="basscontent_maincontent_catelog_item4-basscontent_maincontent_catelog_item4">
          <div className="basscontent_maincontent_catelog_item4-0">
              <div className="basscontent_maincontent_catelog_item4-rectangle-0">
                  <div className="basscontent_maincontent_catelog_item4-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/29d5/1ea3/29e51a73b063b42b1a47e84ab64a2922" className="basscontent_maincontent_catelog_item4-image-0" /> 
                  </div>
                  <div className="basscontent_maincontent_catelog_item4-0-0-1">
                      <div className="basscontent_maincontent_catelog_item4-fender_limited_edition_american_elite_jazz_bass_v_matching_headcap_maple_fingerboard_surf_pearl-0">
                          Fender Limited Edition American Elite Jazz Bass V Matching Headcap Maple Fingerboard Surf Pearl
                      </div>
                  </div>
                  <div className="basscontent_maincontent_catelog_item4-0-0-2">
                      <div className="basscontent_maincontent_catelog_item4-rectangle_2">
                          <div className="basscontent_maincontent_catelog_item4-0-0-2-0-0">
                              <div className="basscontent_maincontent_catelog_item4-guitarcontent_maincontainer_catelog_stars-0">
                                  <div className="basscontent_maincontent_catelog_item4-0-0-2-0-0-0-0">
                                      <div className="basscontent_maincontent_catelog_item4-2">
                                          22 Reviews
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="basscontent_maincontent_catelog_item4-0-0-3">
                      <div className="basscontent_maincontent_catelog_item4-_2">
                          $2099.99
                      </div>
                  </div>
                  <div className="basscontent_maincontent_catelog_item4-0-0-4">
                      <div className="basscontent_maincontent_catelog_item4-guitarciontent_maincontainer_catelog_compare-0">
                          <div className="basscontent_maincontent_catelog_item4-0-0-4-0-0">
                              <div className="basscontent_maincontent_catelog_item4-0-0-4-0-0-0">
                                  <div className="basscontent_maincontent_catelog_item4-0-0-4-0-0-0-0">
                                      <div className="basscontent_maincontent_catelog_item4-rectangle_2-0" /> 
                                  </div>
                              </div>
                              <div className="basscontent_maincontent_catelog_item4-compare-0">
                                  Compare
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
