// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './basscontent_maincontainer.css';


export default class Basscontent_maincontainer extends React.Component {
  render() {
    return (
      <div className="basscontent_maincontainer-basscontent_maincontainer-0">
          <div className="basscontent_maincontainer-0">
              <div className="basscontent_maincontainer-0-0">
                  <div className="basscontent_maincontainer-0-0-0">
                      <div className="basscontent_maincontainer-basscontent_maincontainer_subcat1">
                          <div className="basscontent_maincontainer-0-0-0-0-0">
                              <div className="basscontent_maincontainer-rectangle_2">
                                  <div className="basscontent_maincontainer-0-0-0-0-0-0-0">
                                      <div className="basscontent_maincontainer-subcategories-0">
                                          Subcategories
                                      </div>
                                  </div>
                                  <div className="basscontent_maincontainer-0-0-0-0-0-0-1">
                                      <div className="basscontent_maincontainer-acoustic_bass-0">
                                          Acoustic Bass
                                      </div>
                                  </div>
                                  <div className="basscontent_maincontainer-0-0-0-0-0-0-2">
                                      <div className="basscontent_maincontainer-electric_bass-0">
                                          Electric Bass
                                      </div>
                                  </div>
                                  <div className="basscontent_maincontainer-0-0-0-0-0-0-3">
                                      <div className="basscontent_maincontainer-electric_upright_bass-0">
                                          Electric Upright Bass
                                      </div>
                                  </div>
                                  <div className="basscontent_maincontainer-0-0-0-0-0-0-4">
                                      <div className="basscontent_maincontainer-kits-0">
                                          Kits
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="basscontent_maincontainer-0-0-1">
                      <div className="basscontent_maincontainer-rectangle_2-00000">
                          <div className="basscontent_maincontainer-0-0-1-0-0">
                              <div className="basscontent_maincontainer-brands-0">
                                  Brands
                              </div>
                          </div>
                          <div className="basscontent_maincontainer-0-0-1-0-1">
                              <div className="basscontent_maincontainer-rectangle_3-0">
                                  <div className="basscontent_maincontainer-0-0-1-0-1-0-0">
                                      <div className="basscontent_maincontainer-0-0-1-0-1-0-0-0">
                                          <div className="basscontent_maincontainer-0-0-1-0-1-0-0-0-0">
                                              <div className="basscontent_maincontainer-search_by_brand-0">
                                                  Search by brand
                                              </div>
                                          </div>
                                      </div>
                                      <div className="basscontent_maincontainer-rectangle_3" /> 
                                  </div>
                              </div>
                          </div>
                          <div className="basscontent_maincontainer-0-0-1-0-2">
                              <div className="basscontent_maincontainer-0-0-1-0-2-0">
                                  <div className="basscontent_maincontainer-0-0-1-0-2-0-0">
                                      <div className="basscontent_maincontainer-0-0-1-0-2-0-0-0">
                                          <div className="basscontent_maincontainer-rectangle_2-0" /> 
                                          <div className="basscontent_maincontainer-guitarcontent_maincontainer_subcat2" /> 
                                          <div className="basscontent_maincontainer-guitarcontent_maincontainer_subcat2_">
                                              <div className="basscontent_maincontainer-0-0-1-0-2-0-0-0-2-0">
                                                  <div className="basscontent_maincontainer-rectangle_2-00">
                                                      <div className="basscontent_maincontainer-0-0-1-0-2-0-0-0-2-0-0-0">
                                                          <div className="basscontent_maincontainer-0-0-1-0-2-0-0-0-2-0-0-0-0">
                                                              <div className="basscontent_maincontainer-0-0-1-0-2-0-0-0-2-0-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-rectangle_3-00" /> 
                                                              </div>
                                                          </div>
                                                          <div className="basscontent_maincontainer-dean-0">
                                                              Dean
                                                          </div>
                                                          <div className="basscontent_maincontainer-_3">
                                                              {"(378)"}
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                          <div className="basscontent_maincontainer-guitarcontent_maincontainer_subcat2_i">
                                              <div className="basscontent_maincontainer-0-0-1-0-2-0-0-0-3-0">
                                                  <div className="basscontent_maincontainer-0-0-1-0-2-0-0-0-3-0-0">
                                                      <div className="basscontent_maincontainer-0-0-1-0-2-0-0-0-3-0-0-0">
                                                          <div className="basscontent_maincontainer-rectangle_3-000" /> 
                                                      </div>
                                                  </div>
                                                  <div className="basscontent_maincontainer-esp-0">ESP</div>
                                                  <div className="basscontent_maincontainer-_37">
                                                      {"(378)"}
                                                  </div>
                                              </div>
                                          </div>
                                          <div className="basscontent_maincontainer-rectangle_2-000">
                                              <div className="basscontent_maincontainer-0-0-1-0-2-0-0-0-4-0">
                                                  <div className="basscontent_maincontainer-0-0-1-0-2-0-0-0-4-0-0">
                                                      <div className="basscontent_maincontainer-0-0-1-0-2-0-0-0-4-0-0-0">
                                                          <div className="basscontent_maincontainer-rectangle_3-0000" /> 
                                                      </div>
                                                  </div>
                                                  <div className="basscontent_maincontainer-fender-0">
                                                      Fender
                                                  </div>
                                                  <div className="basscontent_maincontainer-_378">
                                                      {"(378)"}
                                                  </div>
                                              </div>
                                          </div>
                                          <div className="basscontent_maincontainer-rectangle_2-0000">
                                              <div className="basscontent_maincontainer-0-0-1-0-2-0-0-0-5-0">
                                                  <div className="basscontent_maincontainer-guitarcontent_maincontainer_subcat2_it">
                                                      <div className="basscontent_maincontainer-0-0-1-0-2-0-0-0-5-0-0-0">
                                                          <div className="basscontent_maincontainer-0-0-1-0-2-0-0-0-5-0-0-0-0">
                                                              <div className="basscontent_maincontainer-0-0-1-0-2-0-0-0-5-0-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-rectangle_3-00000" /> 
                                                              </div>
                                                          </div>
                                                          <div className="basscontent_maincontainer-ernie_ball-0">
                                                              Ernie Ball
                                                          </div>
                                                          <div className="basscontent_maincontainer-_378_">
                                                              {"(378)"}
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="basscontent_maincontainer-0-1">
                  <div className="basscontent_maincontainer-0-1-0">
                      <div className="basscontent_maincontainer-0-1-0-0">
                          <div className="basscontent_maincontainer-frame-0">
                              <div className="basscontent_maincontainer-0-1-0-0-0-0">
                                  <div className="basscontent_maincontainer-basscontent_maincontent_catelog_item1">
                                      <div className="basscontent_maincontainer-0-1-0-0-0-0-0-0">
                                          <div className="basscontent_maincontainer-rectangle-0">
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-0-0-0-0">
                                                  <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/a0be/951c/1f76807b8449e81a7318a07ee2a1027d" className="basscontent_maincontainer-image-4" /> 
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-0-0-0-1">
                                                  <div className="basscontent_maincontainer-fender_special_edition_deluxe_pj_bass-0">
                                                      Fender Special Edition Deluxe PJ Bass
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-0-0-0-2">
                                                  <div className="basscontent_maincontainer-rectangle_2-000002">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-0-0-0-0-2-0-0">
                                                          <div className="basscontent_maincontainer-guitarcontent_maincontainer_catelog_stars-0">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-0-0-0-2-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-2">
                                                                      22 Reviews
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-0-0-0-3">
                                                  <div className="basscontent_maincontainer-_7">$799.99</div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-0-0-0-4">
                                                  <div className="basscontent_maincontainer-guitarciontent_maincontainer_catelog_compare-0">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-0-0-0-0-4-0-0">
                                                          <div className="basscontent_maincontainer-0-1-0-0-0-0-0-0-0-4-0-0-0">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-0-0-0-4-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-rectangle_2-0000027" /> 
                                                              </div>
                                                          </div>
                                                          <div className="basscontent_maincontainer-compare-0">
                                                              Compare
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="basscontent_maincontainer-basscontent_maincontent_catelog_item2">
                                      <div className="basscontent_maincontainer-0-1-0-0-0-0-1-0">
                                          <div className="basscontent_maincontainer-rectangle-00">
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-1-0-0-0">
                                                  <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/ab20/35af/8d6b496cc35133bccb4bd5d5de027a48" className="basscontent_maincontainer-image-0" /> 
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-1-0-0-1">
                                                  <div className="basscontent_maincontainer-ibanez_gsrm2">
                                                      Ibanez GSRM20 Mikro Short-Scale Bass Guitar
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-1-0-0-2">
                                                  <div className="basscontent_maincontainer-rectangle_2-0000028">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-0-1-0-0-2-0-0">
                                                          <div className="basscontent_maincontainer-guitarcontent_maincontainer_catelog_stars-00">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-1-0-0-2-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-22">
                                                                      22 Reviews
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-1-0-0-3">
                                                  <div className="basscontent_maincontainer-starting_at_1">
                                                      Starting at $159.99
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-1-0-0-4">
                                                  <div className="basscontent_maincontainer-guitarciontent_maincontainer_catelog_compare-00">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-0-1-0-0-4-0-0">
                                                          <div className="basscontent_maincontainer-0-1-0-0-0-0-1-0-0-4-0-0-0">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-1-0-0-4-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-rectangle_2-000003" /> 
                                                              </div>
                                                          </div>
                                                          <div className="basscontent_maincontainer-compare-00">
                                                              Compare
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="basscontent_maincontainer-basscontent_maincontent_catelog_item3">
                                      <div className="basscontent_maincontainer-0-1-0-0-0-0-2-0">
                                          <div className="basscontent_maincontainer-rectangle-000">
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-2-0-0-0">
                                                  <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/f3af/cf26/45c87662d1e4ff39ae29f9d60969d7e7" className="basscontent_maincontainer-image-2" /> 
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-2-0-0-1">
                                                  <div className="basscontent_maincontainer-fender_usa_geddy_lee_signature_jazz_bass-0">
                                                      Fender USA Geddy Lee Signature Jazz Bass
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-2-0-0-2">
                                                  <div className="basscontent_maincontainer-guitarcontent_maincontainer_catelog_stars-000">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-0-2-0-0-2-0-0">
                                                          <div className="basscontent_maincontainer-rectangle_2-000001">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-2-0-0-2-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-22_">
                                                                      22 Reviews
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-2-0-0-3">
                                                  <div className="basscontent_maincontainer-_1">
                                                      $1599.99
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-2-0-0-4">
                                                  <div className="basscontent_maincontainer-guitarciontent_maincontainer_catelog_compare-000">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-0-2-0-0-4-0-0">
                                                          <div className="basscontent_maincontainer-0-1-0-0-0-0-2-0-0-4-0-0-0">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-2-0-0-4-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-rectangle_2-000000" /> 
                                                              </div>
                                                          </div>
                                                          <div className="basscontent_maincontainer-compare-000">
                                                              Compare
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="basscontent_maincontainer-basscontent_maincontent_catelog_item4">
                                      <div className="basscontent_maincontainer-0-1-0-0-0-0-3-0">
                                          <div className="basscontent_maincontainer-rectangle-0000">
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-3-0-0-0">
                                                  <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/29d5/1ea3/29e51a73b063b42b1a47e84ab64a2922" className="basscontent_maincontainer-image-5" /> 
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-3-0-0-1">
                                                  <div className="basscontent_maincontainer-fender_limited_edition_american_elite_jazz_bass_v_matching_headcap_maple_fingerboard_surf_pearl-0">
                                                      Fender Limited Edition American Elite Jazz Bass V Matching Headcap Maple Fingerboard Surf Pearl
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-3-0-0-2">
                                                  <div className="basscontent_maincontainer-rectangle_2-0000029">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-0-3-0-0-2-0-0">
                                                          <div className="basscontent_maincontainer-guitarcontent_maincontainer_catelog_stars-0000">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-3-0-0-2-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-22_r">
                                                                      22 Reviews
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-3-0-0-3">
                                                  <div className="basscontent_maincontainer-_2">
                                                      $2099.99
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-3-0-0-4">
                                                  <div className="basscontent_maincontainer-guitarciontent_maincontainer_catelog_compare-0000">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-0-3-0-0-4-0-0">
                                                          <div className="basscontent_maincontainer-0-1-0-0-0-0-3-0-0-4-0-0-0">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-0-3-0-0-4-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-rectangle_2-0000023" /> 
                                                              </div>
                                                          </div>
                                                          <div className="basscontent_maincontainer-compare-0000">
                                                              Compare
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="basscontent_maincontainer-0-1-0-0-0-1">
                                  <div className="basscontent_maincontainer-basscontent_maincontent_catelog_item4-0">
                                      <div className="basscontent_maincontainer-0-1-0-0-0-1-0-0">
                                          <div className="basscontent_maincontainer-rectangle-00000">
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-0-0-0-0">
                                                  <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/29d5/1ea3/29e51a73b063b42b1a47e84ab64a2922" className="basscontent_maincontainer-image-56" /> 
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-0-0-0-1">
                                                  <div className="basscontent_maincontainer-fender_limited_edition_american_elite_jazz_bass_v_matching_headcap_maple_fingerboard_surf_pearl-00">
                                                      Fender Limited Edition American Elite Jazz Bass V Matching Headcap Maple Fingerboard Surf Pearl
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-0-0-0-2">
                                                  <div className="basscontent_maincontainer-guitarcontent_maincontainer_catelog_stars-00000">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-1-0-0-0-2-0-0">
                                                          <div className="basscontent_maincontainer-rectangle_2-0000002">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-0-0-0-2-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-22_re">
                                                                      22 Reviews
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-0-0-0-3">
                                                  <div className="basscontent_maincontainer-_20">
                                                      $2099.99
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-0-0-0-4">
                                                  <div className="basscontent_maincontainer-guitarciontent_maincontainer_catelog_compare-00000">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-1-0-0-0-4-0-0">
                                                          <div className="basscontent_maincontainer-0-1-0-0-0-1-0-0-0-4-0-0-0">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-0-0-0-4-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-rectangle_2-0000038" /> 
                                                              </div>
                                                          </div>
                                                          <div className="basscontent_maincontainer-compare-00000">
                                                              Compare
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="basscontent_maincontainer-basscontent_maincontent_catelog_item3-0">
                                      <div className="basscontent_maincontainer-0-1-0-0-0-1-1-0">
                                          <div className="basscontent_maincontainer-rectangle-000001">
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-1-0-0-0">
                                                  <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/f3af/cf26/45c87662d1e4ff39ae29f9d60969d7e7" className="basscontent_maincontainer-image-08" /> 
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-1-0-0-1">
                                                  <div className="basscontent_maincontainer-fender_usa_geddy_lee_signature_jazz_bass-00">
                                                      Fender USA Geddy Lee Signature Jazz Bass
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-1-0-0-2">
                                                  <div className="basscontent_maincontainer-guitarcontent_maincontainer_catelog_stars-000004">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-1-1-0-0-2-0-0">
                                                          <div className="basscontent_maincontainer-rectangle_2-0000039">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-1-0-0-2-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-22_rev">
                                                                      22 Reviews
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-1-0-0-3">
                                                  <div className="basscontent_maincontainer-_15">
                                                      $1599.99
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-1-0-0-4">
                                                  <div className="basscontent_maincontainer-guitarciontent_maincontainer_catelog_compare-000003">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-1-1-0-0-4-0-0">
                                                          <div className="basscontent_maincontainer-0-1-0-0-0-1-1-0-0-4-0-0-0">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-1-0-0-4-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-rectangle_2-00000284" /> 
                                                              </div>
                                                          </div>
                                                          <div className="basscontent_maincontainer-compare-000000">
                                                              Compare
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="basscontent_maincontainer-basscontent_maincontent_catelog_item2-0">
                                      <div className="basscontent_maincontainer-0-1-0-0-0-1-2-0">
                                          <div className="basscontent_maincontainer-rectangle-000000">
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-2-0-0-0">
                                                  <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/ab20/35af/8d6b496cc35133bccb4bd5d5de027a48" className="basscontent_maincontainer-image-9" /> 
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-2-0-0-1">
                                                  <div className="basscontent_maincontainer-ibanez_gsrm20">
                                                      Ibanez GSRM20 Mikro Short-Scale Bass Guitar
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-2-0-0-2">
                                                  <div className="basscontent_maincontainer-guitarcontent_maincontainer_catelog_stars-000001">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-1-2-0-0-2-0-0">
                                                          <div className="basscontent_maincontainer-rectangle_2-0000012">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-2-0-0-2-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-22_revi">
                                                                      22 Reviews
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-2-0-0-3">
                                                  <div className="basscontent_maincontainer-starting_at_15">
                                                      Starting at $159.99
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-2-0-0-4">
                                                  <div className="basscontent_maincontainer-guitarciontent_maincontainer_catelog_compare-000000">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-1-2-0-0-4-0-0">
                                                          <div className="basscontent_maincontainer-0-1-0-0-0-1-2-0-0-4-0-0-0">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-2-0-0-4-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-rectangle_2-0000018" /> 
                                                              </div>
                                                          </div>
                                                          <div className="basscontent_maincontainer-compare-000001">
                                                              Compare
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="basscontent_maincontainer-rectangle-000003">
                                      <div className="basscontent_maincontainer-0-1-0-0-0-1-3-0">
                                          <div className="basscontent_maincontainer-basscontent_maincontent_catelog_item1-0">
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-3-0-0-0">
                                                  <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/a0be/951c/1f76807b8449e81a7318a07ee2a1027d" className="basscontent_maincontainer-image-59" /> 
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-3-0-0-1">
                                                  <div className="basscontent_maincontainer-fender_special_edition_deluxe_pj_bass-00">
                                                      Fender Special Edition Deluxe PJ Bass
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-3-0-0-2">
                                                  <div className="basscontent_maincontainer-rectangle_2-00000281">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-1-3-0-0-2-0-0">
                                                          <div className="basscontent_maincontainer-guitarcontent_maincontainer_catelog_stars-000000">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-3-0-0-2-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-22_revie">
                                                                      22 Reviews
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-3-0-0-3">
                                                  <div className="basscontent_maincontainer-_79">
                                                      $799.99
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-3-0-0-4">
                                                  <div className="basscontent_maincontainer-guitarciontent_maincontainer_catelog_compare-000002">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-1-3-0-0-4-0-0">
                                                          <div className="basscontent_maincontainer-0-1-0-0-0-1-3-0-0-4-0-0-0">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-1-3-0-0-4-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-rectangle_2-0000030" /> 
                                                              </div>
                                                          </div>
                                                          <div className="basscontent_maincontainer-compare-000003">
                                                              Compare
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="basscontent_maincontainer-0-1-0-0-0-2">
                                  <div className="basscontent_maincontainer-rectangle-0000034">
                                      <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0">
                                          <div className="basscontent_maincontainer-guitarcontent_maincontainer_header-0">
                                              <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0">
                                                  <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-0">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-0-0">
                                                          <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-0-0-0">
                                                              <div className="basscontent_maincontainer-3">3,543</div>
                                                              <div className="basscontent_maincontainer-items-0">
                                                                  Items
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                                  <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-1">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-1-0">
                                                          <div className="basscontent_maincontainer-display_-0">
                                                              {"Display:"}
                                                          </div>
                                                      </div>
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-1-1">
                                                          <div className="basscontent_maincontainer-guitarconent_maincontainer_dropdown-0">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-1-1-0-0">
                                                                  <div className="basscontent_maincontainer-rectangle_2-0000026">
                                                                      <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-1-1-0-0-0-0">
                                                                          <div className="basscontent_maincontainer-8">
                                                                              8 Products
                                                                          </div>
                                                                      </div>
                                                                  </div>
                                                                  <div className="basscontent_maincontainer-rectangle_2_" /> 
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                                  <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-2">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-2-0">
                                                          <div className="basscontent_maincontainer-sort_by_-0">
                                                              {"Sort By:"}
                                                          </div>
                                                      </div>
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-2-1">
                                                          <div className="basscontent_maincontainer-guitarconent_maincontainer_dropdown-00">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-2-1-0-0">
                                                                  <div className="basscontent_maincontainer-rectangle_2-0000008">
                                                                      <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-2-1-0-0-0-0">
                                                                          <div className="basscontent_maincontainer-best_matches-0">
                                                                              Best Matches
                                                                          </div>
                                                                      </div>
                                                                  </div>
                                                                  <div className="basscontent_maincontainer-rectangle_2_1" /> 
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                                  <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-3">
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-3-0">
                                                          <div className="basscontent_maincontainer-_page_-0">
                                                              {"<<  <  Page  >  >>"}
                                                          </div>
                                                      </div>
                                                      <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-3-1">
                                                          <div className="basscontent_maincontainer-guitarcontent_maincontainer_pagenavbox-0">
                                                              <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-3-1-0-0">
                                                                  <div className="basscontent_maincontainer-0-1-0-0-0-2-0-0-0-0-3-1-0-0-0">
                                                                      <div className="basscontent_maincontainer-1">1</div>
                                                                      <div className="basscontent_maincontainer-rectangle_2-000004" /> 
                                                                  </div>
                                                              </div>
                                                          </div>
                                                          <div className="basscontent_maincontainer-of_4">
                                                              of 454
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="basscontent_maincontainer-rectangle-0000037">
                              <div className="basscontent_maincontainer-0-1-0-0-1-0">
                                  <div className="basscontent_maincontainer-basscontent_maincontainer_header-0">
                                      <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0">
                                          <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-0">
                                              <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-0-0">
                                                  <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-0-0-0">
                                                      <div className="basscontent_maincontainer-3_">3,543</div>
                                                      <div className="basscontent_maincontainer-items-00">
                                                          Items
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                          <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-1">
                                              <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-1-0">
                                                  <div className="basscontent_maincontainer-display_-00">
                                                      {"Display:"}
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-1-1">
                                                  <div className="basscontent_maincontainer-guitarconent_maincontainer_dropdown-000">
                                                      <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-1-1-0-0">
                                                          <div className="basscontent_maincontainer-rectangle_2-0000011">
                                                              <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-1-1-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-8_">
                                                                      8 Products
                                                                  </div>
                                                              </div>
                                                          </div>
                                                          <div className="basscontent_maincontainer-rectangle_2_1-0" /> 
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                          <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-2">
                                              <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-2-0">
                                                  <div className="basscontent_maincontainer-sort_by_-00">
                                                      {"Sort By:"}
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-2-1">
                                                  <div className="basscontent_maincontainer-guitarconent_maincontainer_dropdown-0000">
                                                      <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-2-1-0-0">
                                                          <div className="basscontent_maincontainer-rectangle_2-0000036">
                                                              <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-2-1-0-0-0-0">
                                                                  <div className="basscontent_maincontainer-best_matches-00">
                                                                      Best Matches
                                                                  </div>
                                                              </div>
                                                          </div>
                                                          <div className="basscontent_maincontainer-rectangle_2_1-00" /> 
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                          <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-3">
                                              <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-3-0">
                                                  <div className="basscontent_maincontainer-_page_-00">
                                                      {"<<  <  Page  >  >>"}
                                                  </div>
                                              </div>
                                              <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-3-1">
                                                  <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-3-1-0">
                                                      <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-3-1-0-0">
                                                          <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-3-1-0-0-0">
                                                              <div className="basscontent_maincontainer-1-0">1</div>
                                                              <div className="basscontent_maincontainer-guitarcontent_maincontainer_pagenavbox-00">
                                                                  <div className="basscontent_maincontainer-0-1-0-0-1-0-0-0-3-1-0-0-0-1-0">
                                                                      <div className="basscontent_maincontainer-rectangle_2-00000292" /> 
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                                  <div className="basscontent_maincontainer-of_45">
                                                      of 454
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
