// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './guitardetailcontent_maincontent.css';


export default class Guitardetailcontent_maincontent extends React.Component {
  render() {
    return (
      <div className="guitardetailcontent_maincontent-guitardetailcontent_maincontent-0">
          <div className="guitardetailcontent_maincontent-0">
              <div className="guitardetailcontent_maincontent-g_l_limited_edition_tribute_asat_classic_bluesboy_electric_guitar_turquoise_mist-0">
                  {"G&L Limited Edition Tribute ASAT Classic Bluesboy Electric Guitar Turquoise Mist"}
              </div>
          </div>
          <div className="guitardetailcontent_maincontent-1">
              <div className="guitardetailcontent_maincontent-14">
                  144 Reviews
              </div>
          </div>
          <div className="guitardetailcontent_maincontent-2">
              <div className="guitardetailcontent_maincontent-rectangle-0">
                  <div className="guitardetailcontent_maincontent-2-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/aa5a/776a/832b40712ce37de86414b2aee50ae07f" className="guitardetailcontent_maincontent-image-1" /> 
                  </div>
              </div>
              <div className="guitardetailcontent_maincontent-2-1">
                  <div className="guitardetailcontent_maincontent-2-1-0">
                      <div className="guitardetailcontent_maincontent-2-1-0-0">
                          <div className="guitardetailcontent_maincontent-2-1-0-0-0">
                              <div className="guitardetailcontent_maincontent-_3">
                                  $349.99
                              </div>
                          </div>
                      </div>
                      <div className="guitardetailcontent_maincontent-2-1-0-1">
                          <div className="guitardetailcontent_maincontent-2-1-0-1-0">
                              <div className="guitardetailcontent_maincontent-was_4">
                                  Was $449.99
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="guitardetailcontent_maincontent-2-1-1">
                      <div className="guitardetailcontent_maincontent-save_1">
                          {"Save $100.00  (22% Discount)"}
                      </div>
                  </div>
                  <div className="guitardetailcontent_maincontent-2-1-2">
                      <div className="guitardetailcontent_maincontent-rectangle_2">
                          <div className="guitardetailcontent_maincontent-2-1-2-0-0">
                              <div className="guitardetailcontent_maincontent-free_shipping-0">
                                  FREE SHIPPING
                              </div>
                          </div>
                      </div>
                      <div className="guitardetailcontent_maincontent-2-1-2-1">
                          <div className="guitardetailcontent_maincontent-2-1-2-1-0">
                              <div className="guitardetailcontent_maincontent-4">
                                  48 Contigious U.S. States
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="guitardetailcontent_maincontent-2-1-3">
                      <div className="guitardetailcontent_maincontent-product_info_x_x_x_x_x_x_x-0">
                          <div>{"Product Info:"}</div>
                          <div>x</div>
                          <div>x</div>
                          <div>x</div>
                          <div>x</div>
                          <div>x</div>
                          <div>x</div>
                          <div>x</div>
                      </div>
                  </div>
                  <div className="guitardetailcontent_maincontent-2-1-4">
                      <div className="guitardetailcontent_maincontent-in_stock_ready_to_ship-0">
                          In Stock. Ready To Ship
                      </div>
                  </div>
                  <div className="guitardetailcontent_maincontent-2-1-5">
                      <div className="guitardetailcontent_maincontent-2-1-5-0">
                          <div className="guitardetailcontent_maincontent-2-1-5-0-0">
                              <div className="guitardetailcontent_maincontent-2-1-5-0-0-0">
                                  <div className="guitardetailcontent_maincontent-guitardetailcontent_maincontent_quantityselector-0">
                                      <div className="guitardetailcontent_maincontent-2-1-5-0-0-0-0-0">
                                          <div className="guitardetailcontent_maincontent-rectangle_2-0" /> 
                                          <div className="guitardetailcontent_maincontent-rectangle_2_" /> 
                                      </div>
                                  </div>
                                  <div className="guitardetailcontent_maincontent-1-0">
                                      1
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div className="guitardetailcontent_maincontent-2-1-5-1">
                          <div className="guitardetailcontent_maincontent-2-1-5-1-0">
                              <div className="guitardetailcontent_maincontent-guitardetailcontent_maincontent_addtocartbutton-0">
                                  <div className="guitardetailcontent_maincontent-2-1-5-1-0-0-0">
                                      <div className="guitardetailcontent_maincontent-rectangle_2-00">
                                          <div className="guitardetailcontent_maincontent-2-1-5-1-0-0-0-0-0">
                                              <div className="guitardetailcontent_maincontent-add_to_cart-0">
                                                  Add To Cart
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="guitardetailcontent_maincontent-2-1-6">
                      <div className="guitardetailcontent_maincontent-guitardetailcontent_maincontent_wishlistalertbutton-0">
                          <div className="guitardetailcontent_maincontent-2-1-6-0-0">
                              <div className="guitardetailcontent_maincontent-2-1-6-0-0-0">
                                  <div className="guitardetailcontent_maincontent-rectangle_2_1" /> 
                                  <div className="guitardetailcontent_maincontent-rectangle_2-000" /> 
                                  <div className="guitardetailcontent_maincontent-set_alert-0">
                                      Set Alert
                                  </div>
                                  <div className="guitardetailcontent_maincontent-add_to_wish_list-0">
                                      Add to Wish List
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="guitardetailcontent_maincontent-3">
              <div className="guitardetailcontent_maincontent-image-4">
                  <div className="guitardetailcontent_maincontent-3-0-0">
                      <div className="guitardetailcontent_maincontent-download_7" /> 
                  </div>
              </div>
              <div className="guitardetailcontent_maincontent-image-8">
                  <div className="guitardetailcontent_maincontent-3-1-0">
                      <div className="guitardetailcontent_maincontent-download_8" /> 
                  </div>
              </div>
              <div className="guitardetailcontent_maincontent-image-0">
                  <div className="guitardetailcontent_maincontent-3-2-0">
                      <div className="guitardetailcontent_maincontent-download_9" /> 
                  </div>
              </div>
              <div className="guitardetailcontent_maincontent-image-84">
                  <div className="guitardetailcontent_maincontent-3-3-0">
                      <div className="guitardetailcontent_maincontent-download_1" /> 
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
