// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './guitarcontent_maincontainer_catelog_item2.css';


export default class Guitarcontent_maincontainer_catelog_item2 extends React.Component {
  render() {
    return (
      <div className="guitarcontent_maincontainer_catelog_item2-guitarcontent_maincontainer_catelog_item2">
          <div className="guitarcontent_maincontainer_catelog_item2-0">
              <div className="guitarcontent_maincontainer_catelog_item2-rectangle-0">
                  <div className="guitarcontent_maincontainer_catelog_item2-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/c15d/5025/3ebfa64a72fc84688fa0308e9e2da04e" className="guitarcontent_maincontainer_catelog_item2-image-5" /> 
                  </div>
                  <div className="guitarcontent_maincontainer_catelog_item2-0-0-1">
                      <div className="guitarcontent_maincontainer_catelog_item2-d_angelico_premier_series_dc_with_stop_tail_piece_hollowbody_electric_guitar-0">
                          {"D’Angelico Premier Series DC with Stop Tail Piece HollowBody Electric Guitar"}
                      </div>
                  </div>
                  <div className="guitarcontent_maincontainer_catelog_item2-0-0-2">
                      <div className="guitarcontent_maincontainer_catelog_item2-rectangle_2">
                          <div className="guitarcontent_maincontainer_catelog_item2-0-0-2-0-0">
                              <div className="guitarcontent_maincontainer_catelog_item2-guitarcontent_maincontainer_catelog_stars-0">
                                  <div className="guitarcontent_maincontainer_catelog_item2-0-0-2-0-0-0-0">
                                      <div className="guitarcontent_maincontainer_catelog_item2-1">
                                          104 Reviews
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="guitarcontent_maincontainer_catelog_item2-0-0-3">
                      <div className="guitarcontent_maincontainer_catelog_item2-_6">
                          $699.99
                      </div>
                  </div>
                  <div className="guitarcontent_maincontainer_catelog_item2-0-0-4">
                      <div className="guitarcontent_maincontainer_catelog_item2-guitarciontent_maincontainer_catelog_compare-0">
                          <div className="guitarcontent_maincontainer_catelog_item2-0-0-4-0-0">
                              <div className="guitarcontent_maincontainer_catelog_item2-0-0-4-0-0-0">
                                  <div className="guitarcontent_maincontainer_catelog_item2-0-0-4-0-0-0-0">
                                      <div className="guitarcontent_maincontainer_catelog_item2-rectangle_2-0" /> 
                                  </div>
                              </div>
                              <div className="guitarcontent_maincontainer_catelog_item2-compare-0">
                                  Compare
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
