// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './guitarcontent_maincontent_catelog_item1.css';


export default class Guitarcontent_maincontent_catelog_item1 extends React.Component {
  render() {
    return (
      <div className="guitarcontent_maincontent_catelog_item1-guitarcontent_maincontent_catelog_item1">
          <div className="guitarcontent_maincontent_catelog_item1-0">
              <div className="guitarcontent_maincontent_catelog_item1-rectangle-0">
                  <div className="guitarcontent_maincontent_catelog_item1-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/70ee/4427/4f8f420381676b4f57902825c223627f" className="guitarcontent_maincontent_catelog_item1-image-9" /> 
                  </div>
                  <div className="guitarcontent_maincontent_catelog_item1-0-0-1">
                      <div className="guitarcontent_maincontent_catelog_item1-g_l_limited_edition_tribute_asat_classic_ash_body_electric_guitar-0">
                          {"G&L Limited Edition Tribute ASAT Classic Ash Body Electric Guitar"}
                      </div>
                  </div>
                  <div className="guitarcontent_maincontent_catelog_item1-0-0-2">
                      <div className="guitarcontent_maincontent_catelog_item1-guitarcontent_maincontainer_catelog_stars-0">
                          <div className="guitarcontent_maincontent_catelog_item1-0-0-2-0-0">
                              <div className="guitarcontent_maincontent_catelog_item1-rectangle_2">
                                  <div className="guitarcontent_maincontent_catelog_item1-0-0-2-0-0-0-0">
                                      <div className="guitarcontent_maincontent_catelog_item1-1">
                                          144 Reviews
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="guitarcontent_maincontent_catelog_item1-0-0-3">
                      <div className="guitarcontent_maincontent_catelog_item1-_3">
                          $399.99
                      </div>
                  </div>
                  <div className="guitarcontent_maincontent_catelog_item1-0-0-4">
                      <div className="guitarcontent_maincontent_catelog_item1-guitarciontent_maincontainer_catelog_compare-0">
                          <div className="guitarcontent_maincontent_catelog_item1-0-0-4-0-0">
                              <div className="guitarcontent_maincontent_catelog_item1-0-0-4-0-0-0">
                                  <div className="guitarcontent_maincontent_catelog_item1-0-0-4-0-0-0-0">
                                      <div className="guitarcontent_maincontent_catelog_item1-rectangle_2-0" /> 
                                  </div>
                              </div>
                              <div className="guitarcontent_maincontent_catelog_item1-compare-0">
                                  Compare
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
