// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './guitarcontent_maincontainer_catelog_item4.css';


export default class Guitarcontent_maincontainer_catelog_item4 extends React.Component {
  render() {
    return (
      <div className="guitarcontent_maincontainer_catelog_item4-guitarcontent_maincontainer_catelog_item4">
          <div className="guitarcontent_maincontainer_catelog_item4-0">
              <div className="guitarcontent_maincontainer_catelog_item4-rectangle-0">
                  <div className="guitarcontent_maincontainer_catelog_item4-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/63a9/e81e/4403e82c88e34a39992eaf1c26cfb2e0" className="guitarcontent_maincontainer_catelog_item4-image-5" /> 
                  </div>
                  <div className="guitarcontent_maincontainer_catelog_item4-0-0-1">
                      <div className="guitarcontent_maincontainer_catelog_item4-g_l_limited_edition_tribuite_asat_classic_bluesboy_electric_guitar_turquoise_mist-0">
                          {"G&L Limited Edition Tribuite ASAT Classic Bluesboy Electric Guitar Turquoise Mist"}
                      </div>
                  </div>
                  <div className="guitarcontent_maincontainer_catelog_item4-0-0-2">
                      <div className="guitarcontent_maincontainer_catelog_item4-guitarcontent_maincontainer_catelog_stars-0">
                          <div className="guitarcontent_maincontainer_catelog_item4-0-0-2-0-0">
                              <div className="guitarcontent_maincontainer_catelog_item4-rectangle_2">
                                  <div className="guitarcontent_maincontainer_catelog_item4-0-0-2-0-0-0-0">
                                      <div className="guitarcontent_maincontainer_catelog_item4-2">
                                          22 Reviews
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="guitarcontent_maincontainer_catelog_item4-0-0-3">
                      <div className="guitarcontent_maincontainer_catelog_item4-_3">
                          $349.99
                      </div>
                  </div>
                  <div className="guitarcontent_maincontainer_catelog_item4-0-0-4">
                      <div className="guitarcontent_maincontainer_catelog_item4-guitarciontent_maincontainer_catelog_compare-0">
                          <div className="guitarcontent_maincontainer_catelog_item4-0-0-4-0-0">
                              <div className="guitarcontent_maincontainer_catelog_item4-0-0-4-0-0-0">
                                  <div className="guitarcontent_maincontainer_catelog_item4-0-0-4-0-0-0-0">
                                      <div className="guitarcontent_maincontainer_catelog_item4-rectangle_2-0" /> 
                                  </div>
                              </div>
                              <div className="guitarcontent_maincontainer_catelog_item4-compare-0">
                                  Compare
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
