// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './guitarcontent_maincontainer_catelog_item3.css';


export default class Guitarcontent_maincontainer_catelog_item3 extends React.Component {
  render() {
    return (
      <div className="guitarcontent_maincontainer_catelog_item3-guitarcontent_maincontainer_catelog_item3">
          <div className="guitarcontent_maincontainer_catelog_item3-0">
              <div className="guitarcontent_maincontainer_catelog_item3-rectangle-0">
                  <div className="guitarcontent_maincontainer_catelog_item3-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/40ec/9810/ccbf59dc78d97aa8483d3304ce93728f" className="guitarcontent_maincontainer_catelog_item3-image-6" /> 
                  </div>
                  <div className="guitarcontent_maincontainer_catelog_item3-0-0-1">
                      <div className="guitarcontent_maincontainer_catelog_item3-d_angelico_premier_series_ss_semi-hollowbody_electric_guitar_with_stairstep_tailpiece-0">
                          {"D’Angelico Premier Series SS Semi-Hollowbody Electric Guitar with Stairstep Tailpiece"}
                      </div>
                  </div>
                  <div className="guitarcontent_maincontainer_catelog_item3-0-0-2">
                      <div className="guitarcontent_maincontainer_catelog_item3-rectangle_2">
                          <div className="guitarcontent_maincontainer_catelog_item3-0-0-2-0-0">
                              <div className="guitarcontent_maincontainer_catelog_item3-guitarcontent_maincontainer_catelog_stars-0">
                                  <div className="guitarcontent_maincontainer_catelog_item3-0-0-2-0-0-0-0">
                                      <div className="guitarcontent_maincontainer_catelog_item3-2">
                                          22 Reviews
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="guitarcontent_maincontainer_catelog_item3-0-0-3">
                      <div className="guitarcontent_maincontainer_catelog_item3-_7">
                          $749.99
                      </div>
                  </div>
                  <div className="guitarcontent_maincontainer_catelog_item3-0-0-4">
                      <div className="guitarcontent_maincontainer_catelog_item3-guitarciontent_maincontainer_catelog_compare-0">
                          <div className="guitarcontent_maincontainer_catelog_item3-0-0-4-0-0">
                              <div className="guitarcontent_maincontainer_catelog_item3-0-0-4-0-0-0">
                                  <div className="guitarcontent_maincontainer_catelog_item3-0-0-4-0-0-0-0">
                                      <div className="guitarcontent_maincontainer_catelog_item3-rectangle_2-0" /> 
                                  </div>
                              </div>
                              <div className="guitarcontent_maincontainer_catelog_item3-compare-0">
                                  Compare
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
