// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './guitarcontent_maincontainer_header.css';


export default class Guitarcontent_maincontainer_header extends React.Component {
  render() {
    return (
      <div className="guitarcontent_maincontainer_header-guitarcontent_maincontainer_header-0">
          <div className="guitarcontent_maincontainer_header-0">
              <div className="guitarcontent_maincontainer_header-rectangle-0">
                  <div className="guitarcontent_maincontainer_header-0-0-0">
                      <div className="guitarcontent_maincontainer_header-0-0-0-0">
                          <div className="guitarcontent_maincontainer_header-0-0-0-0-0">
                              <div className="guitarcontent_maincontainer_header-0-0-0-0-0-0">
                                  <div className="guitarcontent_maincontainer_header-3">
                                      3,543
                                  </div>
                                  <div className="guitarcontent_maincontainer_header-items-0">
                                      Items
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div className="guitarcontent_maincontainer_header-0-0-0-1">
                          <div className="guitarcontent_maincontainer_header-0-0-0-1-0">
                              <div className="guitarcontent_maincontainer_header-display_-0">
                                  {"Display:"}
                              </div>
                          </div>
                          <div className="guitarcontent_maincontainer_header-0-0-0-1-1">
                              <div className="guitarcontent_maincontainer_header-guitarconent_maincontainer_dropdown-0">
                                  <div className="guitarcontent_maincontainer_header-0-0-0-1-1-0-0">
                                      <div className="guitarcontent_maincontainer_header-rectangle_2">
                                          <div className="guitarcontent_maincontainer_header-0-0-0-1-1-0-0-0-0">
                                              <div className="guitarcontent_maincontainer_header-8">
                                                  8 Products
                                              </div>
                                          </div>
                                      </div>
                                      <div className="guitarcontent_maincontainer_header-rectangle_2_" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div className="guitarcontent_maincontainer_header-0-0-0-2">
                          <div className="guitarcontent_maincontainer_header-0-0-0-2-0">
                              <div className="guitarcontent_maincontainer_header-sort_by_-0">
                                  {"Sort By:"}
                              </div>
                          </div>
                          <div className="guitarcontent_maincontainer_header-0-0-0-2-1">
                              <div className="guitarcontent_maincontainer_header-guitarconent_maincontainer_dropdown-00">
                                  <div className="guitarcontent_maincontainer_header-0-0-0-2-1-0-0">
                                      <div className="guitarcontent_maincontainer_header-rectangle_2-0">
                                          <div className="guitarcontent_maincontainer_header-0-0-0-2-1-0-0-0-0">
                                              <div className="guitarcontent_maincontainer_header-best_matches-0">
                                                  Best Matches
                                              </div>
                                          </div>
                                      </div>
                                      <div className="guitarcontent_maincontainer_header-rectangle_2_1" /> 
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div className="guitarcontent_maincontainer_header-0-0-0-3">
                          <div className="guitarcontent_maincontainer_header-0-0-0-3-0">
                              <div className="guitarcontent_maincontainer_header-_page_-0">
                                  {"<<  <  Page  >  >>"}
                              </div>
                          </div>
                          <div className="guitarcontent_maincontainer_header-0-0-0-3-1">
                              <div className="guitarcontent_maincontainer_header-guitarcontent_maincontainer_pagenavbox-0">
                                  <div className="guitarcontent_maincontainer_header-0-0-0-3-1-0-0">
                                      <div className="guitarcontent_maincontainer_header-0-0-0-3-1-0-0-0">
                                          <div className="guitarcontent_maincontainer_header-1">
                                              1
                                          </div>
                                          <div className="guitarcontent_maincontainer_header-rectangle_2-00" /> 
                                      </div>
                                  </div>
                              </div>
                              <div className="guitarcontent_maincontainer_header-of_4">
                                  of 454
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
