// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './header_top_button_sign-in.css';


export default class Header_top_button_sign_in extends React.Component {
  render() {
    return (
      <div className="header_top_button_sign-in-header_top_button_sign-in-0">
          <div className="header_top_button_sign-in-0">
              <div className="header_top_button_sign-in-rectangle-0">
                  <div className="header_top_button_sign-in-0-0-0">
                      <div className="header_top_button_sign-in-sign_in-0">
                          Sign In
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
