// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './header_banner1.css';


export default class Header_banner1 extends React.Component {
  render() {
    return (
      <div className="header_banner1-header_banner1">
          <div className="header_banner1-0">
              <div className="header_banner1-rectangle-0">
                  <div className="header_banner1-0-0-0">
                      <div className="header_banner1-0-0-0-0">
                          <div className="header_banner1-0-0-0-0-0">
                              <div className="header_banner1-0-0-0-0-0-0">
                                  <div className="header_banner1-1">1-800-472-6274</div>
                                  <div className="header_banner1-speak_to_an_expert-0">
                                      SPEAK TO AN EXPERT
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="header_banner1-0-0-1">
                      <div className="header_banner1-customer_service_international_sales-0">
                          {"CUSTOMER SERVICE | INTERNATIONAL SALES"}
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
