// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './header_menu_dropdownbutton.css';


export default class Header_menu_dropdownbutton extends React.Component {
  render() {
    return (
      <div className="header_menu_dropdownbutton-header_menu_dropdownbutton-0">
          <div className="header_menu_dropdownbutton-0">
              <div className="header_menu_dropdownbutton-rectangle-0">
                  <div className="header_menu_dropdownbutton-0-0-0">
                      <div className="header_menu_dropdownbutton-featured_departments-0">
                          Featured Departments
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
