// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './header.css';


export default class Header extends React.Component {
  render() {
    return (
      <div className="header-header-00">
          <div className="header-0">
              <div className="header-header-0">
                  <div className="header-0-0-0">
                      <div className="header-0-0-0-0">
                          <div className="header-rectangle-0000015">
                              <div className="header-0-0-0-0-0-0">
                                  <div className="header-rectangle-000004">
                                      <div className="header-0-0-0-0-0-0-0-0">
                                          <div className="header-0-0-0-0-0-0-0-0-0">
                                              <div className="header-0-0-0-0-0-0-0-0-0-0">
                                                  <div className="header-button_menu_sign-in-0">
                                                      <div className="header-0-0-0-0-0-0-0-0-0-0-0-0">
                                                          <div className="header-rectangle-0">
                                                              <div className="header-0-0-0-0-0-0-0-0-0-0-0-0-0-0">
                                                                  <div className="header-sign_in-0">Sign In</div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                          <div className="header-button_menu_gift-0">
                                              <div className="header-0-0-0-0-0-0-0-0-1-0">
                                                  <div className="header-rectangle-00">
                                                      <div className="header-0-0-0-0-0-0-0-0-1-0-0-0">
                                                          <div className="header-gift_certificate-0">
                                                              Gift Certificate
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                          <div className="header-0-0-0-0-0-0-0-0-2">
                                              <div className="header-0-0-0-0-0-0-0-0-2-0">
                                                  <div className="header-rectangle-000">
                                                      <div className="header-0-0-0-0-0-0-0-0-2-0-0-0">
                                                          <div className="header-button_menu_ordertracking-0">
                                                              <div className="header-0-0-0-0-0-0-0-0-2-0-0-0-0-0">
                                                                  <div className="header-order_tracking-0">
                                                                      Order Tracking
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                          <div className="header-0-0-0-0-0-0-0-0-3">
                                              <div className="header-0-0-0-0-0-0-0-0-3-0">
                                                  <div className="header-button_menu_wishlist-0">
                                                      <div className="header-0-0-0-0-0-0-0-0-3-0-0-0">
                                                          <div className="header-rectangle-0000">
                                                              <div className="header-0-0-0-0-0-0-0-0-3-0-0-0-0-0">
                                                                  <div className="header-wish_list-0">Wish List</div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                          <div className="header-0-0-0-0-0-0-0-0-4">
                                              <div className="header-0-0-0-0-0-0-0-0-4-0">
                                                  <div className="header-button_menu_help-0">
                                                      <div className="header-0-0-0-0-0-0-0-0-4-0-0-0">
                                                          <div className="header-rectangle-00000">
                                                              <div className="header-0-0-0-0-0-0-0-0-4-0-0-0-0-0">
                                                                  <div className="header-help-0">Help</div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div className="header-0-0-0-0-0-1">
                                  <div className="header-logo-0">
                                      <div className="header-0-0-0-0-0-1-0-0">
                                          <div className="header-rectangle-000001">
                                              <div className="header-0-0-0-0-0-1-0-0-0-0">
                                                  <div className="header-0-0-0-0-0-1-0-0-0-0-0">
                                                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/41cc/2e37/f9c065329733dd380b8d4efa12daa81b" className="header-image-8" /> 
                                                      <div className="header-music_instruments_pro_audio_dj_gear-0">
                                                          MUSIC INSTRUMENTS / PRO AUDIO / DJ GEAR
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="header-0-0-0-0-0-1-1">
                                      <div className="header-0-0-0-0-0-1-1-0">
                                          <div className="header-banner1">
                                              <div className="header-0-0-0-0-0-1-1-0-0-0">
                                                  <div className="header-rectangle-000000">
                                                      <div className="header-0-0-0-0-0-1-1-0-0-0-0-0">
                                                          <div className="header-0-0-0-0-0-1-1-0-0-0-0-0-0">
                                                              <div className="header-0-0-0-0-0-1-1-0-0-0-0-0-0-0">
                                                                  <div className="header-0-0-0-0-0-1-1-0-0-0-0-0-0-0-0">
                                                                      <div className="header-1">1-800-472-6274</div>
                                                                      <div className="header-speak_to_an_expert-0">
                                                                          SPEAK TO AN EXPERT
                                                                      </div>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div className="header-0-0-0-0-0-1-1-0-0-0-0-1">
                                                          <div className="header-customer_service_international_sales-0">
                                                              {"CUSTOMER SERVICE | INTERNATIONAL SALES"}
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div className="header-rectangle-000002">
                              <div className="header-0-0-0-0-1-0">
                                  <div className="header-0-0-0-0-1-0-0">
                                      <div className="header-0-0-0-0-1-0-0-0">
                                          <div className="header-dropdownitem_dept-0">
                                              <div className="header-0-0-0-0-1-0-0-0-0-0">
                                                  <div className="header-rectangle-0000012">
                                                      <div className="header-0-0-0-0-1-0-0-0-0-0-0-0">
                                                          <div className="header-featured_departments-0">
                                                              Featured Departments
                                                          </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="header-0-0-0-0-1-0-1">
                                      <div className="header-0-0-0-0-1-0-1-0">
                                          <div className="header-rectangle-000003">
                                              <div className="header-0-0-0-0-1-0-1-0-0-0">
                                                  <div className="header-dropdownitem_brand-0">
                                                      <div className="header-0-0-0-0-1-0-1-0-0-0-0-0">
                                                          <div className="header-shop_by_brand-0">Shop By Brand</div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="header-0-0-0-0-1-0-2">
                                      <div className="header-0-0-0-0-1-0-2-0">
                                          <div className="header-searchbar-0">
                                              <div className="header-0-0-0-0-1-0-2-0-0-0">
                                                  <div className="header-0-0-0-0-1-0-2-0-0-0-0">
                                                      <div className="header-rectangle-0000016" /> 
                                                      <div className="header-rectangle-0000041" /> 
                                                      <div className="header-search-0">SEARCH</div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="header-0-0-0-0-1-0-3">
                                      <div className="header-0-0-0-0-1-0-3-0">
                                          <div className="header-header_menu_dropdownbutton-0">
                                              <div className="header-0-0-0-0-1-0-3-0-0-0">
                                                  <div className="header-rectangle-0000002">
                                                      <div className="header-0-0-0-0-1-0-3-0-0-0-0-0">
                                                          <div className="header-cart-0">CART</div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
