// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './logo.css';


export default class Logo extends React.Component {
  render() {
    return (
      <div className="logo-logo-0">
          <div className="logo-0">
              <div className="logo-rectangle-0">
                  <div className="logo-0-0-0">
                      <div className="logo-0-0-0-0">
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/41cc/2e37/f9c065329733dd380b8d4efa12daa81b" className="logo-image-6" /> 
                          <div className="logo-music_instruments_pro_audio_dj_gear-0">
                              MUSIC INSTRUMENTS / PRO AUDIO / DJ GEAR
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
