// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './maincontent_deptcat_guitar.css';


export default class Maincontent_deptcat_guitar extends React.Component {
  render() {
    return (
      <div onClick={this.props.onClick} className="maincontent_deptcat_guitar-maincontent_deptcat_guitar-0">
          <div className="maincontent_deptcat_guitar-0">
              <div className="maincontent_deptcat_guitar-rectangle-00">
                  <div className="maincontent_deptcat_guitar-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/4cdc/fb4a/5994bf70324a5a512afa52c17d7131ca" className="maincontent_deptcat_guitar-image-3" /> 
                  </div>
                  <div className="maincontent_deptcat_guitar-0-0-1">
                      <div className="maincontent_deptcat_guitar-rectangle-0" /> 
                  </div>
                  <div className="maincontent_deptcat_guitar-0-0-2">
                      <div className="maincontent_deptcat_guitar-guitar-0">
                          Guitar
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
