// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './maincontent_deptcat_drums.css';


export default class Maincontent_deptcat_drums extends React.Component {
  render() {
    return (
      <div className="maincontent_deptcat_drums-maincontent_deptcat_drums-0">
          <div className="maincontent_deptcat_drums-0">
              <div className="maincontent_deptcat_drums-rectangle-00">
                  <div className="maincontent_deptcat_drums-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/cc2d/6219/d63d3a09ce8be7f6ac4da67e4c6d6ce8" className="maincontent_deptcat_drums-image-1" /> 
                  </div>
                  <div className="maincontent_deptcat_drums-0-0-1">
                      <div className="maincontent_deptcat_drums-rectangle-0" /> 
                  </div>
                  <div className="maincontent_deptcat_drums-0-0-2">
                      <div className="maincontent_deptcat_drums-drums_percussion-0">
                          {"Drums & Percussion"}
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
