// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './maincontent_deptcat_recording.css';


export default class Maincontent_deptcat_recording extends React.Component {
  render() {
    return (
      <div className="maincontent_deptcat_recording-maincontent_deptcat_recording-0">
          <div className="maincontent_deptcat_recording-0">
              <div className="maincontent_deptcat_recording-rectangle-00">
                  <div className="maincontent_deptcat_recording-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/d74e/432d/7a8c921d520a1177dfb5e27bd667394b" className="maincontent_deptcat_recording-image-1" /> 
                  </div>
                  <div className="maincontent_deptcat_recording-0-0-1">
                      <div className="maincontent_deptcat_recording-rectangle-0" /> 
                  </div>
                  <div className="maincontent_deptcat_recording-0-0-2">
                      <div className="maincontent_deptcat_recording-recording-0">
                          Recording
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
