// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './maincontent_popularitems_drums.css';


export default class Maincontent_popularitems_drums extends React.Component {
  render() {
    return (
      <div className="maincontent_popularitems_drums-maincontent_popularitems_drums-0">
          <div className="maincontent_popularitems_drums-0">
              <div className="maincontent_popularitems_drums-0-0">
                  <div className="maincontent_popularitems_drums-rectangle_2">
                      <div className="maincontent_popularitems_drums-0-0-0-0">
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/effa/9c9d/51a61d1c048c8fb8232b64561ba4eb9e" className="maincontent_popularitems_drums-image-3" /> 
                      </div>
                  </div>
                  <div className="maincontent_popularitems_drums-_2">
                      $299.99
                  </div>
                  <div className="maincontent_popularitems_drums-simmons_sd3">
                      Simmons SD350 Electronic Drum Kit with Mesh Pads
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
