// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './maincontent_popularitems_mic.css';


export default class Maincontent_popularitems_mic extends React.Component {
  render() {
    return (
      <div className="maincontent_popularitems_mic-maincontent_popularitems_mic-0">
          <div className="maincontent_popularitems_mic-0">
              <div className="maincontent_popularitems_mic-0-0">
                  <div className="maincontent_popularitems_mic-rectangle_2">
                      <div className="maincontent_popularitems_mic-0-0-0-0">
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/3a40/1956/5466b18119562a08c03be5f637ba8445" className="maincontent_popularitems_mic-image-3" /> 
                      </div>
                      <div className="maincontent_popularitems_mic-0-0-0-1">
                          <div className="maincontent_popularitems_mic-digital_reference_drv2">
                              Digital Reference DRV200 Dynamic Lead Vocal Mic
                          </div>
                      </div>
                  </div>
                  <div className="maincontent_popularitems_mic-_2">
                      $29.99
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
