// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './maincontent_deptcat_accessories.css';


export default class Maincontent_deptcat_accessories extends React.Component {
  render() {
    return (
      <div className="maincontent_deptcat_accessories-maincontent_deptcat_accessories-0">
          <div className="maincontent_deptcat_accessories-0">
              <div className="maincontent_deptcat_accessories-rectangle-00">
                  <div className="maincontent_deptcat_accessories-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/1868/e168/0305b5a90a7c1a6f95b94bd77def9e7d" className="maincontent_deptcat_accessories-image-3" /> 
                  </div>
                  <div className="maincontent_deptcat_accessories-0-0-1">
                      <div className="maincontent_deptcat_accessories-rectangle-0" /> 
                  </div>
                  <div className="maincontent_deptcat_accessories-0-0-2">
                      <div className="maincontent_deptcat_accessories-accessories-0">
                          Accessories
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
