// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './maincontent_ad_discount.css';


export default class Maincontent_ad_discount extends React.Component {
  render() {
    return (
      <div className="maincontent_ad_discount-maincontent_ad_discount-0">
          <div className="maincontent_ad_discount-0">
              <div className="maincontent_ad_discount-0-0">
                  <div className="maincontent_ad_discount-rectangle-0" /> 
                  <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/3a41/69e4/5d2547e7de295558ca7e598dc949c726" className="maincontent_ad_discount-image-1" /> 
                  <div className="maincontent_ad_discount-rectangle_2" /> 
                  <div className="maincontent_ad_discount-all_new_gear-0">
                      All New Gear
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
