// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './maincontent_ad_clearance.css';


export default class Maincontent_ad_clearance extends React.Component {
  render() {
    return (
      <div className="maincontent_ad_clearance-maincontent_ad_clearance-0">
          <div className="maincontent_ad_clearance-0">
              <div className="maincontent_ad_clearance-image-2">
                  <div className="maincontent_ad_clearance-0-0-0">
                      <div className="maincontent_ad_clearance-rectangle_3">
                          <div className="maincontent_ad_clearance-0-0-0-0-0">
                              <div className="maincontent_ad_clearance-this_week_only-0">
                                  this week only
                              </div>
                          </div>
                          <div className="maincontent_ad_clearance-0-0-0-0-1">
                              <div className="maincontent_ad_clearance-0-0-0-0-1-0">
                                  <div className="maincontent_ad_clearance-0-0-0-0-1-0-0">
                                      <div className="maincontent_ad_clearance-0-0-0-0-1-0-0-0">
                                          <div className="maincontent_ad_clearance-clearance-0">
                                              CLEARANCE
                                          </div>
                                          <div className="maincontent_ad_clearance-clearance-00" /> 
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
