// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './maincontent_deptcat_bass.css';


export default class Maincontent_deptcat_bass extends React.Component {
  render() {
    return (
      <div className="maincontent_deptcat_bass-maincontent_deptcat_bass-0">
          <div className="maincontent_deptcat_bass-0">
              <div className="maincontent_deptcat_bass-rectangle-00">
                  <div className="maincontent_deptcat_bass-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/1e21/1d69/a8ffd24f6dce65314afb86cede6fce26" className="maincontent_deptcat_bass-image-1" /> 
                  </div>
                  <div className="maincontent_deptcat_bass-0-0-1">
                      <div className="maincontent_deptcat_bass-rectangle-0" /> 
                  </div>
                  <div className="maincontent_deptcat_bass-0-0-2">
                      <div className="maincontent_deptcat_bass-bass-0">Bass</div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
