// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './maincontent_popularitems_guitar.css';


export default class Maincontent_popularitems_guitar extends React.Component {
  render() {
    return (
      <div className="maincontent_popularitems_guitar-maincontent_popularitems_guitar-0">
          <div className="maincontent_popularitems_guitar-0">
              <div className="maincontent_popularitems_guitar-0-0">
                  <div className="maincontent_popularitems_guitar-rectangle_2">
                      <div className="maincontent_popularitems_guitar-0-0-0-0">
                          <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/ed82/1837/944a61b54e8175f1337e6c2495396dd7" className="maincontent_popularitems_guitar-image-3" /> 
                      </div>
                  </div>
                  <div className="maincontent_popularitems_guitar-_4">
                      $49.99
                  </div>
                  <div className="maincontent_popularitems_guitar-rogue_ra-0">
                      Rogue RA-090 Dreadnought Acoustic Guitar
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
