// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './maincontent_deptcat_keys.css';


export default class Maincontent_deptcat_keys extends React.Component {
  render() {
    return (
      <div className="maincontent_deptcat_keys-maincontent_deptcat_keys-0">
          <div className="maincontent_deptcat_keys-0">
              <div className="maincontent_deptcat_keys-rectangle-00">
                  <div className="maincontent_deptcat_keys-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/3e98/29e4/b7b3b19be831162f2eb50cfb13251366" className="maincontent_deptcat_keys-image-4" /> 
                  </div>
                  <div className="maincontent_deptcat_keys-0-0-1">
                      <div className="maincontent_deptcat_keys-rectangle-0" /> 
                  </div>
                  <div className="maincontent_deptcat_keys-0-0-2">
                      <div className="maincontent_deptcat_keys-keyboards_midi-0">
                          {"Keyboards & MIDI"}
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
