// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './maincontent_deptcat_mic.css';


export default class Maincontent_deptcat_mic extends React.Component {
  render() {
    return (
      <div className="maincontent_deptcat_mic-maincontent_deptcat_mic-0">
          <div className="maincontent_deptcat_mic-0">
              <div className="maincontent_deptcat_mic-rectangle-00">
                  <div className="maincontent_deptcat_mic-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/3b4a/753c/63240986a100c0d0833ddfd4bfa32bb3" className="maincontent_deptcat_mic-image-0" /> 
                  </div>
                  <div className="maincontent_deptcat_mic-0-0-1">
                      <div className="maincontent_deptcat_mic-rectangle-0" /> 
                  </div>
                  <div className="maincontent_deptcat_mic-0-0-2">
                      <div className="maincontent_deptcat_mic-mics_wireless-0">
                          {"Mics & Wireless"}
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
