// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './maincontent_deptcat_livesound.css';


export default class Maincontent_deptcat_livesound extends React.Component {
  render() {
    return (
      <div className="maincontent_deptcat_livesound-maincontent_deptcat_livesound-0">
          <div className="maincontent_deptcat_livesound-0">
              <div className="maincontent_deptcat_livesound-rectangle-00">
                  <div className="maincontent_deptcat_livesound-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/ca59/659c/81f68ec70d26422aa2f94c0d528bc1a1" className="maincontent_deptcat_livesound-image-8" /> 
                  </div>
                  <div className="maincontent_deptcat_livesound-0-0-1">
                      <div className="maincontent_deptcat_livesound-rectangle-0" /> 
                  </div>
                  <div className="maincontent_deptcat_livesound-0-0-2">
                      <div className="maincontent_deptcat_livesound-live_sound-0">
                          Live Sound
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
