// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './maincontent_deptcat_amp.css';


export default class Maincontent_deptcat_amp extends React.Component {
  render() {
    return (
      <div className="maincontent_deptcat_amp-maincontent_deptcat_amp-0">
          <div className="maincontent_deptcat_amp-0">
              <div className="maincontent_deptcat_amp-rectangle-00">
                  <div className="maincontent_deptcat_amp-0-0-0">
                      <img src="https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/046a/3946/06b69f0816e66bee9a0542733972b5ff" className="maincontent_deptcat_amp-image-1" /> 
                  </div>
                  <div className="maincontent_deptcat_amp-0-0-1">
                      <div className="maincontent_deptcat_amp-rectangle-0" /> 
                  </div>
                  <div className="maincontent_deptcat_amp-0-0-2">
                      <div className="maincontent_deptcat_amp-amps_effects-0">
                          {"Amps & Effects"}
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
