// Generated by https://pagedraw.io/pages/13588
import React from 'react';
import './searchbar.css';


export default class Searchbar extends React.Component {
  render() {
    return (
      <div className="searchbar-searchbar-0">
          <div className="searchbar-0">
              <div className="searchbar-0-0">
                  <div className="searchbar-rectangle-0" /> 
                  <div className="searchbar-rectangle-00" /> 
                  <div className="searchbar-search-0">SEARCH</div>
              </div>
          </div>
      </div>
    );
  }
};
